service: vision
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1Vision:
    handler: handler.v1Vision
    events:
      - httpApi:
          path: /v1/vision
          method: post
  v2Vision:
    handler: routes/rota2.v2Vision
    events:
      - httpApi:
          path: /v2/vision
          method: post
  v3Vision:
    handler: routes/rota3.v3Vision
    events:
      - httpApi:
          path: /v3/vision
          method: post

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-photos-sprint8      