service: vision
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  postVision:
    handler: routes.route_v1.post_vision
    events:
      - httpApi:
          path: /routes/route_v1/v1/vision
          method: post
  v2Vision:
    handler: routes.route_v2.v2_vision
    events:
      - httpApi:
          path: /routes/route_v2/v2/vision
          method: post
  v3Vision:
    handler: routes.route_v3.v3_vision
    events:
      - httpApi:
          path: /routes/route_v3/v3/vision
          method: post